config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :cocktails, only: [:index, :show, :new, :create] do
    resources :doses, only: [:new, :create]
  end

  resources :doses, only: [:destroy]
  root to: 'cocktails#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cocktail.rb
class Cocktail < ApplicationRecord
  has_many :doses, dependent: :destroy
  has_many :ingredients, -> { distinct }, through: :doses
  validates :name, uniqueness: true, presence: true
end

app/models/dose.rb
class Dose < ApplicationRecord
  belongs_to :cocktail
  belongs_to :ingredient
  validates :description, presence: true
  validates_uniqueness_of :cocktail, scope: :ingredient
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  has_many :doses
  validates :name, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cocktails_controller.rb
class CocktailsController < ApplicationController
  def index
    @cocktails = Cocktail.all
  end

  def show
    @cocktail = Cocktail.find(params[:id])
  end

  def new
    @cocktail = Cocktail.new
  end

  def create
    @cocktail = Cocktail.new(cocktail_params)
    if @cocktail.save
      redirect_to cocktail_path(@cocktail)
    else
      render :new
    end
  end

  private

  def cocktail_params
    params.require(:cocktail).permit(:name)
  end
end

app/controllers/doses_controller.rb
class DosesController < ApplicationController

    def new
      @cocktail = Cocktail.find(params[:cocktail_id])
      @dose = Dose.new
    end

  def create
    @cocktail = Cocktail.find(params[:cocktail_id])
    @dose = Dose.new(dose_params)
    @dose.cocktail = @cocktail
      if @dose.save
        redirect_to cocktail_path(@cocktail)
      else

        render :new
      end
  end


  def destroy
    @dose = Dose.find(params[:id])
    @dose.destroy
  end

  private

  def dose_params
    params.require(:dose).permit(:description, :ingredient_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cocktails_helper.rb
module CocktailsHelper
end

app/helpers/doses_helper.rb
module DosesHelper
end

app/views/cocktails/index.html.erb
 <nav class="navbar">
  <a class="navbar-brand" href="#">CocktailMania</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
</nav>



  <div class="banner-content" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url('https://images.unsplash.com/photo-1546171753-97d7676e4602?ixlib=rb-1.2.1&auto=format&fit=crop&w=634&q=80');">>
    <h1>Cocktails</h1>
    <p>Awesome cocktails</p>
    <%= link_to "Add a cocktail", new_cocktail_path, class: "btn btn-warning btn-lg" %>
  </div>

  <%= simple_form_for :search, url: root_path, method: :get do |f| %>
  <div class="search-form">
    <input class="form-control string required" type="text" name="search[query]" id="search_query" />
    <button name="button" type="submit" class="btn btn-flat">

    </button>
  </div>
<% end %>
<div class="container">
  <div class="row">
    <% @cocktails.each do |cocktail| %>
      <div class="col-12 col-md-6 col-lg-3">
        <div class="card" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url('https://images.unsplash.com/photo-1528498033373-3c6c08e93d79?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=632&q=80');">
          <div class="card-description">
            <h2><%= cocktail.name %></h2>
          </div>
          <%= link_to "", cocktail_path(cocktail), class: 'card-link' %>
        </div>
      </div>
    <% end %>

    <div class="footer">
  <div class="footer-links">
    <a href="#"><i class="fab fa-github"></i></a>
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
    <a href="#"><i class="fab fa-linkedin"></i></a>
  </div>
  <div class="footer-copyright">
    This footer is made with <i class="fas fa-heart"></i> at Le Wagon
  </div>
</div>

  </div>
</div>

app/views/cocktails/new.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-md-8">
      <h1>Create a new cocktail</h1>

      <%= simple_form_for @cocktail do |f| %>
        <%= f.input :name %>
        <%= f.button :submit, class: 'btn btn-warning' %>
      <% end %>
    </div>
  </div>
</div>

app/views/cocktails/show.html.erb
show

<div class="container">

  <h1><%= @cocktail.name %></h1>
  <%= link_to "Back to all cocktails", root_path %>

  <div class="row">
    <div class="col-sm-12 col-md-6">
      <h3>Recipe</h3>
      <table class="table table-bordered">
        <tbody>
          <thead>
            <th>Ingredient</th>
            <th>Description</th>
            <th>Action</th>
          </thead>
          <% @cocktail.doses.each do |dose| %>
            <tr>
              <td><%= dose.ingredient.name %></td>
              <td><%= dose.description %></td>
              <td>
                <%= link_to dose_path(dose), method: :delete, data: { confirm: "Are you sure?" } do %>
                  <i class="fa fa-trash destroy_dose"></i>
                <% end %>
              </td>
            </tr>
          <% end %>
        </tbody>

      </table>
    </div>
  </div>

app/views/doses/new.html.erb
<h3>Add a new dose</h3>
<%= simple_form_for [@cocktail, @dose] do |f| %>
  <%= f.association :ingredient, input_html: { class: "beautiful-dropdown" }, include_hidden: false %>
  <%= f.input :description %>
  <%= f.button :submit, class: "btn btn-primary" %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <head>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <title>RailsMisterCocktail</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
    <%= javascript_include_tag "application" %> <!-- from app/assets/javascripts/application.js -->
  <%= javascript_pack_tag "application" %>    <!-- from app/javascript/packs/application.js -->
  </body>
</html>